Add wheels for boxy and options
code-iai/iai_robots pull request #33
Opened 2020-10-16 12:08 UTC by HoangGiang93

I add wheels for donbot

2020-10-19 13:53 UTC, ichumuh commented
did you forget to add a file?
```
$ roslaunch iai_donbot_description upload_with_refills_finger.launch 
... logging to /home/stelter/.ros/log/d87dfed0-0f9c-11eb-8961-04d4c4ace797/roslaunch-ai-00024-19038.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Undefined parameters [with_wheels,with_boxes]
when instantiating macro: iai_donbot (/home/stelter/iai_ws/src/iai_robots/iai_donbot_description/robots/iai_donbot.xacro)
in file: /home/stelter/iai_ws/src/iai_robots/iai_donbot_description/robots/iai_donbot_with_refills_finger.urdf.xacro
RLException: while processing /home/stelter/iai_ws/src/iai_robots/iai_donbot_description/launch/upload.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/melodic/lib/xacro/xacro', '/home/stelter/iai_ws/src/iai_robots/iai_donbot_description/robots/iai_donbot_with_refills_finger.urdf.xacro', 'transmission_hw_interface:=hardware_interface/PositionJointInterface', 'kinematics_config:=/home/stelter/iai_ws/src/iai_robots/iai_donbot_description/config/ur5_calibration.yaml']] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro '$(arg urdf)' transmission_hw_interface:=$(arg transmission_hw_interface)     kinematics_config:=$(arg kinematics_config)" name="robot_description"/>
The traceback for the exception was written to the log file
```

2020-10-20 09:04 UTC, HoangGiang93 commented
I fixed the bugs, should I make pull request again or it would be automatically updated?

2020-10-20 09:16 UTC, ichumuh commented
it updates automatically, if you push to the same branch, which you did. i'll look at it again soon.

2020-10-20 09:39 UTC, ichumuh requested changes

2020-10-20 09:39 UTC, ichumuh commented on iai_donbot_description/robots/iai_donbot_with_refills_finger.urdf.xacro
> +  <xacro:iai_donbot odom="True" with_wheels="True" with_boxes="False" />
With boxes should be the default. This is the urdf, i'm using on donbot.

2020-10-20 09:39 UTC, ichumuh commented on iai_boxy_base_2/robots/base.xacro
> +			<link name="wheel_left_up">
i think better names would be `wheel_front_left` and so on. up and down don't really make sense.

2020-10-20 09:39 UTC, ichumuh commented on iai_boxy_base_2/robots/base.xacro
> +			<link name="wheel_left_up">
the wheels also appear red in rviz. Can you color them grey?

2020-10-20 09:39 UTC, ichumuh commented on iai_boxy_base_2/robots/base.xacro
> +			<link name="wheel_left_up">
the new wheels overlap with the old ones, that are part of the base_link. if the point is, to make donbot pretty, then the base link mesh needs to be cut into pieces

2020-10-20 09:39 UTC, ichumuh commented on iai_boxy_base_2/robots/base.xacro
> +			<link name="wheel_left_up">
the collision mesh should just be a simple cylinder with the same size as the wheel, to speed up collision checking

2020-10-20 17:26 UTC, HoangGiang93 commented
I fixed all the issues that @ichumuh mentioned

2020-10-21 09:30 UTC, merged

2020-10-21 09:30 UTC, ichumuh commented
look nice, thank!